### ISSUE TITLE
Each page should have a minimum of two (2) paragraphs of text

### ISSUE THREAD

**Issue by mleybov** [jackbertquan/Quality-Assurance-Final-Project#1]
Summary: Each page should have a minimum of two (2) paragraphs of text
Severity: Not severe 
Environment: Chrome 47.0.2526.106
Description: Each page should have a minimum of two (2) paragraphs of text. The main page only had one paragraph of text. Add one more paragraph of text.
Attachment: *pretend I attached main page screen shot here*

**Comment by jackbertquan** [comment]
ffc1b66aacd1798223cee8b4988ed1feedd5ca3d
